/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/DefaultLayout/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    MenuItem: typeof import('./src/components/SideNav/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav/index.vue')['default']
  }
}
